title: Multi-omics of Type 2 Diabetes
description: A place to gather info for my upcoming PhD project
theme: just-the-docs

url: https://hollyanitamartin.github.io/hollyanitamartin.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
